# CoatingObsidian Configuration file
#==================#
#   Basic Config   #
#==================#
# コーティング可能なアイテムIDを設定
# 木材など複数IDあるもの（1:1,1:2など）は『○:□』○の数字扱いです。
# 例：1,2,3,4
# 上記設定で有効になるもの：1,1:1,1:2,1:3,1:4,1:5,1:6,2,3,3:1,3:2,4
coatingItem: 1,2,3,4

#コーティングに必要な黒曜石の数
NumberNecessaryForCoating: 3